import * as path from 'path';
import { ContextSlot, Platform } from '../types';
import { BaseAdapter } from './base';

export class CursorAdapter extends BaseAdapter {
  platform: Platform = 'cursor';
  displayName = 'Cursor';
  outputDir = '.cursor';

  getOutputPath(slot: ContextSlot, _projectRoot: string): string {
    switch (slot.type) {
      case 'rules':
        return path.join(this.outputDir, 'rules', `${slot.name}.mdc`);
      case 'agent':
        return path.join(this.outputDir, 'agents', `${slot.name}.mdc`);
      case 'memory':
        return path.join(this.outputDir, 'memory', `${slot.name}.md`);
      case 'docs':
        return path.join(this.outputDir, 'docs', `${slot.name}.md`);
      default:
        return path.join(this.outputDir, `${slot.name}.md`);
    }
  }

  formatContent(slot: ContextSlot): string {
    const ctxHeader = [
      '<!-- Generated by ctx - DO NOT EDIT DIRECTLY -->',
      `<!-- Source: ${slot.sourcePath} -->`,
      '<!-- To modify, edit the source file above and run: ctx sync -->',
      '<!-- Commands: ctx add <type> <name> | ctx sync | ctx status | ctx diff -->',
      '',
      '',
    ].join('\n');

    if (slot.type === 'rules' || slot.type === 'agent') {
      const frontmatter = [
        '---',
        `description: ${slot.name}`,
        'globs: "*"',
        'alwaysApply: true',
        '---',
        '',
      ].join('\n');
      return frontmatter + ctxHeader + slot.content;
    }

    return ctxHeader + slot.content;
  }
}
