import * as path from 'path';
import { ContextSlot, Platform } from '../types';
import { BaseAdapter } from './base';

export class WindsurfAdapter extends BaseAdapter {
  platform: Platform = 'windsurf';
  displayName = 'Windsurf';
  outputDir = '.windsurf';

  getOutputPath(slot: ContextSlot, _projectRoot: string): string {
    switch (slot.type) {
      case 'rules':
        return path.join(this.outputDir, 'rules', `${slot.name}.md`);
      case 'agent':
        return path.join(this.outputDir, 'agents', `${slot.name}.md`);
      case 'memory':
        return path.join(this.outputDir, 'memory', `${slot.name}.md`);
      case 'docs':
        return path.join(this.outputDir, 'docs', `${slot.name}.md`);
      default:
        return path.join(this.outputDir, `${slot.name}.md`);
    }
  }

  formatContent(slot: ContextSlot): string {
    return `<!-- Generated by ctx -->\n<!-- Source: ${slot.sourcePath} -->\n\n${slot.content}`;
  }
}
